# Generated by Django 4.0.2 on 2022-02-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
